# ============================================================================
# WIZARD HISTORY VIEWER
# ============================================================================
# View past page improvement prompts generated by the wizard.
#
# Usage:
#   .\view-wizard-history.ps1              # List all prompts
#   .\view-wizard-history.ps1 -Page guide  # Filter by page
#   .\view-wizard-history.ps1 -Last 5      # Show last 5
#   .\view-wizard-history.ps1 -Open 1      # Open specific prompt
# ============================================================================

param(
    [string]$Page = "",       # Filter by page name
    [int]$Last = 10,          # Show last N prompts
    [int]$Open = 0,           # Open specific prompt by number
    [switch]$Help             # Show help
)

$promptsDir = Join-Path $PSScriptRoot "prompts"

function Show-Help {
    Write-Host ""
    Write-Host "WIZARD HISTORY VIEWER" -ForegroundColor Cyan
    Write-Host "=====================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "View past page improvement prompts generated by the wizard."
    Write-Host ""
    Write-Host "Usage:" -ForegroundColor Yellow
    Write-Host "  .\view-wizard-history.ps1              # List all prompts"
    Write-Host "  .\view-wizard-history.ps1 -Page guide  # Filter by page"
    Write-Host "  .\view-wizard-history.ps1 -Last 5      # Show last 5"
    Write-Host "  .\view-wizard-history.ps1 -Open 3      # Open prompt #3"
    Write-Host ""
}

if ($Help) {
    Show-Help
    exit 0
}

if (-not (Test-Path $promptsDir)) {
    Write-Host ""
    Write-Host "No prompts found yet." -ForegroundColor Yellow
    Write-Host "Run page-improvement-wizard.ps1 to generate your first prompt."
    Write-Host ""
    exit 0
}

# Get all prompt files
$files = Get-ChildItem -Path $promptsDir -Filter "*.md" | Sort-Object LastWriteTime -Descending

if ($Page) {
    $files = $files | Where-Object { $_.Name -like "$Page-*" }
}

$files = $files | Select-Object -First $Last

if ($files.Count -eq 0) {
    Write-Host ""
    Write-Host "No prompts found$(if ($Page) { " for page '$Page'" })." -ForegroundColor Yellow
    Write-Host ""
    exit 0
}

# Open specific file
if ($Open -gt 0) {
    if ($Open -gt $files.Count) {
        Write-Host "Invalid number. Only $($files.Count) prompts available." -ForegroundColor Red
        exit 1
    }
    
    $fileToOpen = $files[$Open - 1]
    Write-Host ""
    Write-Host "Opening: $($fileToOpen.Name)" -ForegroundColor Green
    Write-Host ""
    
    # Display content
    Get-Content $fileToOpen.FullName
    
    # Copy to clipboard
    Get-Content $fileToOpen.FullName -Raw | Set-Clipboard
    Write-Host ""
    Write-Host "✓ Copied to clipboard!" -ForegroundColor Green
    Write-Host ""
    exit 0
}

# List all prompts
Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║                    WIZARD PROMPT HISTORY                         ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

Write-Host "  #   Page                Date                 Size" -ForegroundColor Gray
Write-Host "  ─── ─────────────────── ──────────────────── ─────" -ForegroundColor Gray

$i = 1
foreach ($file in $files) {
    # Extract page name from filename (format: pagename-2024-12-05_10-30-00.md)
    $pageName = ($file.Name -split "-\d{4}-")[0]
    $date = $file.LastWriteTime.ToString("yyyy-MM-dd HH:mm")
    $size = if ($file.Length -gt 1024) { "$([math]::Round($file.Length / 1024, 1))KB" } else { "$($file.Length)B" }
    
    $numStr = $i.ToString().PadLeft(3)
    $pageStr = $pageName.PadRight(19)
    $dateStr = $date.PadRight(20)
    
    Write-Host "  $numStr $pageStr $dateStr $size"
    $i++
}

Write-Host ""
Write-Host "  Use -Open <number> to view and copy a specific prompt." -ForegroundColor DarkGray
Write-Host "  Example: .\view-wizard-history.ps1 -Open 1" -ForegroundColor DarkGray
Write-Host ""
